SELECT * FROM dual@SITE1_LINK;
SELECT * FROM dual@SITE2_LINK;
BEGIN
    EXECUTE IMMEDIATE 'SELECT 1 FROM DUAL@global_link';
    DBMS_OUTPUT.PUT_LINE('✓ SITE1 → Globale: CONNECTE');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('✗ SITE1 → Globale: NON CONNECTE - ' || SQLERRM);
END;
/