SELECT * FROM dual@SITE1_LINK;
SELECT * FROM dual@SITE2_LINK;
BEGIN
    EXECUTE IMMEDIATE 'SELECT 1 FROM DUAL@global_link';
    DBMS_OUTPUT.PUT_LINE('✓ SITE1 → Globale: CONNECTE');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('✗ SITE1 → Globale: NON CONNECTE - ' || SQLERRM);
END;
/
--  Tests Site 1 :
DECLARE
    v_test NUMBER;
BEGIN
    BEGIN EXECUTE IMMEDIATE 'SELECT 1 FROM DUAL@SITE_GLOBAL' INTO v_test;
        DBMS_OUTPUT.PUT_LINE(' SITE1 → GLOBALE: CONNECTE');
    EXCEPTION WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE(' SITE1 → GLOBALE: ' || SQLERRM);
    END;
    
    BEGIN EXECUTE IMMEDIATE 'SELECT 1 FROM DUAL@SITE2' INTO v_test;
        DBMS_OUTPUT.PUT_LINE(' SITE1 → SITE2: CONNECTE');
    EXCEPTION WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE(' SITE1 → SITE2: ' || SQLERRM);
    END;
END;
/
SELECT DB_LINK, USERNAME, HOST 
FROM USER_DB_LINKS 
ORDER BY DB_LINK;

-- Tests SITE 2:
PROMPT 4. Tests des connexions...
DECLARE
    v_test NUMBER;
BEGIN
    BEGIN EXECUTE IMMEDIATE 'SELECT 1 FROM DUAL@SITE_GLOBAL' INTO v_test;
        DBMS_OUTPUT.PUT_LINE(' SITE2 → GLOBALE: CONNECTE');
    EXCEPTION WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE(' SITE2 → GLOBALE: ' || SQLERRM);
    END;
    
    BEGIN EXECUTE IMMEDIATE 'SELECT 1 FROM DUAL@SITE1' INTO v_test;
        DBMS_OUTPUT.PUT_LINE(' SITE2 → SITE1: CONNECTE');
    EXCEPTION WHEN OTHERS THEN 
        DBMS_OUTPUT.PUT_LINE(' SITE2 → SITE1: ' || SQLERRM);
    END;
END;
/
SELECT DB_LINK, USERNAME, HOST 
FROM USER_DB_LINKS 
ORDER BY DB_LINK;